import { test, expect } from '@playwright/test';
test.use({
  storageState: 'storage/loginState/stage.json'
});

test('test', async ({ page }) => {
  await page.getByRole('button', { name: '新建合同' }).click();
  await page.getByText('请选择合同').click();
  await page.getByRole('option', { name: '合同' }).locator('span').first().click();
  await page.getByRole('button', { name: '确 定' }).click();
  await page.locator('.ant-select-selection__placeholder').first().click();
  await page.getByRole('cell', { name: '-02-11' }).click();
  await page.getByRole('button', { name: '确 定' }).click();
  await page.locator('input[name=7fbac917-1a37-42f9-a929-bf3e0776d27c]').click();
  await page.locator('input[name=7fbac917-1a37-42f9-a929-bf3e0776d27c]').fill('111');
  await page.locator('[id=6117e841-c812-051f-3cd5-3adf0721e8a3] > .ant-row > .ant-col.ant-form-item-control-wrapper > .ant-form-item-control > .ant-form-item-children > .multi-selector-block > .multi-selector-wrapper > .fake-input > .slector-value-content').click();
  await page.locator('div').filter({ hasText: /^宣传展览合同$/ }).first().click();
  await page.locator('.ant-calendar-picker-input').first().click();
  await page.getByRole('grid').getByTitle('年4月8日').locator('div').click();
  await page.locator('[id=7a1b867b-c181-4128-bd8e-9cfb06f670c6] > .ant-row > .ant-col.ant-form-item-control-wrapper > .ant-form-item-control > .ant-form-item-children > .multi-selector-block > .multi-selector-wrapper > .fake-input > .slector-value-content').click();
  await page.getByText('上海实誉智能科技有限公司').click();
  await page.getByText('苏州空动力电子技术有限公司').click();
  await page.locator('.fake-input.fake-input-open > .slector-value-content').click();
  await page.locator('div').filter({ hasText: /^迦递货运代理（上海）有限公司$/ }).first().click();
  await page.locator('#c2444aaf-38db-b521-2aed-becd1e284030 > .ant-row > .ant-col.ant-form-item-control-wrapper > .ant-form-item-control > .ant-form-item-children > .multi-selector-block > .multi-selector-wrapper > .fake-input > .slector-value-content').click();
  await page.getByText('增值税专用发票', { exact: true }).click();
  await page.getByText('增值税电子普通发票（通行费）').click();
  await page.locator('.fake-input.fake-input-open > .slector-value-content').click();
  await page.locator('span').filter({ hasText: '增值税电子普通发票（通行费）' }).click();
  await page.locator('#e3b6e63e-57be-4dab-9d39-2273ab0e5680 > .ant-row > .ant-col.ant-form-item-control-wrapper > .ant-form-item-control > .ant-form-item-children > .ant-calendar-picker > div > .ant-calendar-picker-input').click();
  await page.getByRole('grid').getByTitle('年4月8日').locator('div').click();
  await page.locator('[id=84a560cf-0dcd-4053-b3e2-e78a0f335ad1] > .ant-row > .ant-col.ant-form-item-control-wrapper > .ant-form-item-control > .ant-form-item-children > .ant-calendar-picker > div > .ant-calendar-picker-input').click();
  await page.getByRole('grid').getByTitle('年4月8日').locator('div').click();
  await page.getByText('附件上传').first().click();
  await page.locator('body').setInputFiles('截屏2026-04-07 10.02.44.png');
  await page.getByText('请选择').nth(4).click();
  await page.getByRole('cell', { name: '600005' }).click();
  await page.getByRole('button', { name: '确 定' }).click();
  await page.getByRole('button', { name: '下一步' }).click();
  await page.getByText('管理员0001江苏省精创电气股份有限公司江苏省精创电气股份有限公司（手工）|财务中心').click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByText('展开').click();
  await page.locator('#one-screen-header-info').getByText('收起').click();
  await page.getByText('收起').click();
  await page.locator('#RELATED_COMP').getByText('展开').click();
  await page.getByText('合同公司').click();
  await page.locator('#CUSTOM_FORM').getByText('江苏省精创电气股份有限公司').click();
  await page.getByText('合同名称').click();
  await page.getByText('111').click();
  await page.getByText('合同类型').click();
  await page.getByText('宣传展览合同').click();
  await page.getByText('签署日期').click();
  await page.getByText('-04-08').nth(2).click();
  await page.getByText('有效日期至').click();
  await page.getByText('单据信息编 辑合同公司江苏省精创电气股份有限公司合同名称').click();
  await page.getByText('相对方信息签约主体江苏省精创电气股份有限公司签约对象供应商(1个)序号名称编号姓名电话邮箱操作1迦递货运代理（上海）有限公司QTWL1080019---详情').click();
  await page.locator('#opposite-info').getByRole('img').nth(1).click();
  await page.getByText('详情', { exact: true }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.locator('div').filter({ hasText: /^详情迦递货运代理（上海）有限公司No\. QTWL1080019---$/ }).nth(1).click();
  await page.locator('#opposite-info').getByRole('img').first().click();
  await page.getByText('详情', { exact: true }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.locator('#attachment-list img').click();
  await page.locator('.drag-modal-content-header > div:nth-child(2)').click();
  await page.getByRole('button', { name: '导入申请单费用信息' }).click();
  await page.getByRole('button', { name: '添加费用信息' }).click();
  await page.getByRole('textbox', { name: '请选择' }).click();
  await page.locator('#recommend-history-18b5 span').filter({ hasText: '住宿费' }).getByRole('img').click();
  await page.getByRole('textbox', { name: '请输入或选择' }).click();
  await page.getByRole('button', { name: '今天' }).click();
  await page.getByRole('button', { name: '保 存' }).click();
  await page.getByRole('spinbutton', { name: '0.00' }).click();
  await page.getByRole('spinbutton', { name: '0.00' }).fill('1');
  await page.locator('#slide-content-id').click();
  await page.getByRole('button', { name: '保 存' }).click();
  await page.getByText('复制').nth(1).click();
  await page.getByRole('button', { name: '添加付款信息' }).click();
  await page.getByRole('textbox', { name: '阶段/款项名称' }).click();
  await page.getByRole('textbox', { name: '阶段/款项名称' }).fill('11');
  await page.getByRole('spinbutton', { name: '0.00' }).click();
  await page.getByRole('textbox', { name: '请输入或选择' }).click();
  await page.getByRole('grid').getByTitle('年4月8日').locator('div').click();
  await page.locator('span').filter({ hasText: '迦递货运代理（上海）有限公司457259249125' }).locator('path').first().click();
  await page.getByRole('textbox', { name: '付款条件' }).fill('1');
  await page.getByRole('spinbutton', { name: '0.00' }).fill('1');
  await page.getByRole('textbox', { name: '备注' }).fill('1');
  await page.locator('span').filter({ hasText: '迦递货运代理（上海）有限公司457259249125' }).locator('path').first().click();
  await page.getByRole('button', { name: '确 定' }).click();
  await page.getByRole('button', { name: '保 存' }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(2).click();
  await page.locator('#payment-info').getByRole('button', { name: '批量删除' }).click();
  await page.getByRole('row', { name: '序号 付款行编号 阶段名称 币种 付款比例 金额 本币金额 单价 本币单价 收款方 计划付款日期 付款条件 可关联支付金额 已付款合计金额 待付款在途金额 备注' }).getByLabel('').check();
  await page.getByRole('button', { name: '删 除' }).click();
  await page.getByRole('button', { name: '确 定' }).click();
  await page.getByRole('button', { name: '提 交' }).click();
  await page.getByRole('button', { name: '添加付款信息' }).click();
  await page.getByRole('textbox', { name: '阶段/款项名称' }).click();
  await page.getByRole('textbox', { name: '阶段/款项名称' }).fill('11');
  await page.getByRole('spinbutton', { name: '0.00' }).click();
  await page.getByRole('spinbutton', { name: '0.00' }).fill('1');
  await page.getByRole('textbox', { name: '请输入或选择' }).click();
  await page.getByRole('button', { name: '今天' }).click();
  await page.getByRole('button', { name: '保 存' }).click();
  await page.getByRole('button', { name: '提 交' }).click();
  await page.getByText('收起').click();
  await page.getByRole('button', { name: '返 回' }).click();
});